/**
 * Modal parse provider — talks to the Modal-hosted Docling service over
 * HTTP (multipart). This is the default for the hosted-cloud tier.
 *
 * The deployed Modal app exposes two entry points (see
 * `services/parse-modal/app.py`):
 *
 *   - `parse` — an SDK-invocable `@app.function`. Python-only — there is
 *     no stable Node SDK for remote-invoking a Modal function.
 *   - `parse_http` — a `@modal.fastapi_endpoint(requires_proxy_auth=True)`
 *     that wraps `parse` and accepts a multipart POST. This is what the
 *     Node client targets.
 *
 * The URL is generated by Modal at deploy time (something like
 * `https://<workspace>--koji-parse-parse-http.modal.run`) and must be
 * copied into `KOJI_PARSE_MODAL_URL`. See `services/parse-modal/README.md`
 * for the full wiring flow.
 *
 * Auth is proxy-auth tokens, not the account tokens the Modal CLI uses.
 * Create a proxy token in the Modal dashboard (Settings → Proxy Auth
 * Tokens) and plumb it into the API as `MODAL_TOKEN_ID` /
 * `MODAL_TOKEN_SECRET`. Modal checks the `Modal-Key` and `Modal-Secret`
 * request headers against the proxy token.
 *
 * Modal's fastapi_endpoint proxy has a 150s response-write deadline.
 * If the function is still running when that deadline hits, Modal
 * returns 303 redirecting to a polling URL (same path + a
 * `__modal_function_call_id=fc-...` query param). We have to follow
 * that redirect manually: the RFC says 303 after POST converts to GET
 * (fetch's default does that correctly), but then the POLL URL also
 * returns 303s repeatedly until the function settles, and fetch's
 * default redirect-follow gives up after 20 hops AND has no way to
 * reattach our auth headers cross-origin. So we disable auto-follow
 * and drive the loop ourselves.
 */

import type { ParseProvider, ParseResponse } from "./provider";

const DEFAULT_TIMEOUT_MS = 10 * 60 * 1000; // 10 min — covers L4 cold start + full OCR of large scanned PDFs
const MAX_POLLS = 80; // 80 × 150s = 200 min hard ceiling; real limit is timeoutMs

interface RawParseResponse {
  filename?: string;
  markdown: string;
  pages?: number;
  ocr_skipped?: boolean;
  elapsed_seconds?: number;
  error?: string;
}

export class ModalParseProvider implements ParseProvider {
  private readonly url: string;
  private readonly tokenId: string;
  private readonly tokenSecret: string;
  private readonly timeoutMs: number;

  constructor(opts?: {
    url?: string;
    tokenId?: string;
    tokenSecret?: string;
    timeoutMs?: number;
  }) {
    const url = opts?.url ?? process.env.KOJI_PARSE_MODAL_URL;
    const tokenId = opts?.tokenId ?? process.env.MODAL_TOKEN_ID;
    const tokenSecret = opts?.tokenSecret ?? process.env.MODAL_TOKEN_SECRET;

    if (!url) {
      throw new Error(
        "ModalParseProvider: KOJI_PARSE_MODAL_URL is required (deploy the Modal app and copy the parse-http endpoint URL)",
      );
    }
    if (!tokenId || !tokenSecret) {
      throw new Error(
        "ModalParseProvider: MODAL_TOKEN_ID and MODAL_TOKEN_SECRET are required for proxy auth",
      );
    }

    this.url = url;
    this.tokenId = tokenId;
    this.tokenSecret = tokenSecret;
    this.timeoutMs = opts?.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  }

  async parse(input: {
    filename: string;
    mimeType: string;
    fileBuffer: Buffer;
  }): Promise<ParseResponse> {
    const { filename, mimeType, fileBuffer } = input;
    const deadline = Date.now() + this.timeoutMs;

    // Copy into a fresh ArrayBuffer-backed Uint8Array — Node's
    // `Buffer<ArrayBufferLike>` doesn't unify with DOM's `BlobPart` under
    // strict Workers type libs (ArrayBufferLike includes SharedArrayBuffer).
    // `Uint8Array.from` produces `Uint8Array<ArrayBuffer>`, a valid
    // `BlobPart` in both typesets.
    const part = Uint8Array.from(fileBuffer);
    const form = new FormData();
    form.append("file", new Blob([part], { type: mimeType }), filename);
    form.append("filename", filename);
    form.append("mime_type", mimeType);

    // Initial POST. Disable fetch's built-in redirect follow — we drive
    // the 303 polling loop manually so we can reattach auth headers on
    // each hop and cap total wait time against our own deadline.
    let resp = await this.fetchNoFollow(this.url, {
      method: "POST",
      body: form,
      deadline,
    });

    // Follow the 303 → poll → 303 → ... → 200 chain.
    let pollUrl: string | null = null;
    for (let hop = 0; hop < MAX_POLLS; hop++) {
      if (resp.status === 200) {
        return this.readResponse(resp);
      }

      if (resp.status === 303 || resp.status === 302) {
        const loc = resp.headers.get("location");
        if (!loc) {
          throw new Error(`parse (modal): ${resp.status} with no Location header`);
        }
        // Location can be relative. Resolve against the last URL we spoke to.
        pollUrl = new URL(loc, pollUrl ?? this.url).toString();
        // Drain the body to free the connection.
        await resp.arrayBuffer().catch(() => undefined);
        if (Date.now() >= deadline) {
          throw new Error(
            `parse timeout after ${this.timeoutMs}ms (modal, stuck polling at ${pollUrl})`,
          );
        }
        resp = await this.fetchNoFollow(pollUrl, { method: "GET", deadline });
        continue;
      }

      // Any other status is terminal.
      const body = await resp.text().catch(() => "");
      throw new Error(
        `parse ${resp.status} (modal): ${body.slice(0, 300) || "(empty body)"}`,
      );
    }

    throw new Error(
      `parse (modal): redirect loop exceeded ${MAX_POLLS} hops at ${pollUrl ?? this.url}`,
    );
  }

  /**
   * fetch() wrapper that (a) disables auto-redirect so we can drive the
   * poll loop ourselves, (b) attaches Modal proxy-auth headers on every
   * request, and (c) times out each individual hop against the overall
   * deadline so a hung Modal backend can't wedge us forever.
   */
  private async fetchNoFollow(
    url: string,
    opts: { method: "GET" | "POST"; body?: FormData; deadline: number },
  ): Promise<Response> {
    const remaining = opts.deadline - Date.now();
    if (remaining <= 0) {
      throw new Error("parse timeout (modal) — deadline exceeded before request");
    }
    // Per-hop timeout: cap at remaining budget, but don't exceed 160s
    // (Modal's own proxy deadline is 150s, so anything longer than ~160
    // on a single hop means the server is stuck, not just working).
    const hopTimeout = Math.min(remaining, 160_000);
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), hopTimeout);

    try {
      return await fetch(url, {
        method: opts.method,
        body: opts.body,
        redirect: "manual",
        headers: {
          "Modal-Key": this.tokenId,
          "Modal-Secret": this.tokenSecret,
        },
        signal: controller.signal,
      });
    } catch (err) {
      if ((err as { name?: string }).name === "AbortError") {
        throw new Error(
          `parse (modal) hop timeout: no response from ${url} within ${hopTimeout}ms`,
        );
      }
      throw new Error(
        `parse request failed (modal): ${(err as Error).message ?? String(err)}`,
      );
    } finally {
      clearTimeout(timer);
    }
  }

  private async readResponse(resp: Response): Promise<ParseResponse> {
    const result = (await resp.json()) as RawParseResponse;
    if (!result.markdown) {
      if (result.error) {
        throw new Error(`parse returned error (modal): ${result.error}`);
      }
      throw new Error("parse returned no markdown (modal)");
    }
    return {
      markdown: result.markdown,
      pages: result.pages ?? null,
      ocr_skipped: result.ocr_skipped ?? false,
    };
  }
}
