/**
 * Modal parse provider — talks to the Modal-hosted Docling service over
 * HTTP (multipart). This is the default for the hosted-cloud tier.
 *
 * The deployed Modal app exposes two entry points (see
 * `services/parse-modal/app.py`):
 *
 *   - `parse` — an SDK-invocable `@app.function`. Python-only — there is
 *     no stable Node SDK for remote-invoking a Modal function.
 *   - `parse_http` — a `@modal.fastapi_endpoint(requires_proxy_auth=True)`
 *     that wraps `parse` and accepts a multipart POST. This is what the
 *     Node client targets.
 *
 * The URL is generated by Modal at deploy time (something like
 * `https://<workspace>--koji-parse-parse-http.modal.run`) and must be
 * copied into `KOJI_PARSE_MODAL_URL`. See `services/parse-modal/README.md`
 * for the full wiring flow.
 *
 * Auth is proxy-auth tokens, not the account tokens the Modal CLI uses.
 * Create a proxy token in the Modal dashboard (Settings → Proxy Auth
 * Tokens) and plumb it into the API as `MODAL_TOKEN_ID` /
 * `MODAL_TOKEN_SECRET`. Modal checks the `Modal-Key` and `Modal-Secret`
 * request headers against the proxy token.
 */

import type { ParseProvider, ParseResponse } from "./provider";

const DEFAULT_TIMEOUT_MS = 120_000;

interface RawParseResponse {
  filename?: string;
  markdown: string;
  pages?: number;
  ocr_skipped?: boolean;
  elapsed_seconds?: number;
  error?: string;
}

export class ModalParseProvider implements ParseProvider {
  private readonly url: string;
  private readonly tokenId: string;
  private readonly tokenSecret: string;
  private readonly timeoutMs: number;

  constructor(opts?: {
    url?: string;
    tokenId?: string;
    tokenSecret?: string;
    timeoutMs?: number;
  }) {
    const url = opts?.url ?? process.env.KOJI_PARSE_MODAL_URL;
    const tokenId = opts?.tokenId ?? process.env.MODAL_TOKEN_ID;
    const tokenSecret = opts?.tokenSecret ?? process.env.MODAL_TOKEN_SECRET;

    if (!url) {
      throw new Error(
        "ModalParseProvider: KOJI_PARSE_MODAL_URL is required (deploy the Modal app and copy the parse-http endpoint URL)",
      );
    }
    if (!tokenId || !tokenSecret) {
      throw new Error(
        "ModalParseProvider: MODAL_TOKEN_ID and MODAL_TOKEN_SECRET are required for proxy auth",
      );
    }

    this.url = url;
    this.tokenId = tokenId;
    this.tokenSecret = tokenSecret;
    this.timeoutMs = opts?.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  }

  async parse(input: {
    filename: string;
    mimeType: string;
    fileBuffer: Buffer;
  }): Promise<ParseResponse> {
    const { filename, mimeType, fileBuffer } = input;

    const form = new FormData();
    form.append("file", new Blob([fileBuffer], { type: mimeType }), filename);
    form.append("filename", filename);
    form.append("mime_type", mimeType);

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);

    let resp: Response;
    try {
      resp = await fetch(this.url, {
        method: "POST",
        body: form,
        headers: {
          "Modal-Key": this.tokenId,
          "Modal-Secret": this.tokenSecret,
        },
        signal: controller.signal,
      });
    } catch (err) {
      if ((err as { name?: string }).name === "AbortError") {
        throw new Error(`parse timeout after ${this.timeoutMs}ms (modal)`);
      }
      throw new Error(
        `parse request failed (modal): ${(err as Error).message ?? String(err)}`,
      );
    } finally {
      clearTimeout(timer);
    }

    if (!resp.ok) {
      const body = await resp.text().catch(() => "");
      throw new Error(`parse ${resp.status} (modal): ${body.slice(0, 300)}`);
    }

    const result = (await resp.json()) as RawParseResponse;
    if (!result.markdown) {
      if (result.error) {
        throw new Error(`parse returned error (modal): ${result.error}`);
      }
      throw new Error("parse returned no markdown (modal)");
    }
    return {
      markdown: result.markdown,
      pages: result.pages ?? null,
      ocr_skipped: result.ocr_skipped ?? false,
    };
  }
}
